changelog:
  exclude:
    labels:
      - ignore/changelog
  categories:
    - title: Bug Fixes 🛠
      labels:
        - bug fix
    - title: Enhancements 🛠
      labels:
        - enhancement
    - title: New Features 🎉
      labels:
        - new feature
    - title: Other Changes
      labels:
        - "*"