name: module tests

on:
  push:
    branches:
      - "**"

env:
  terraform_version: "v1.2.6"
  minikube_version: 'v1.26.0'

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${ env.terraform_version }

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

  integration-tests:
    runs-on: ubuntu-latest
    needs:
      - lint
    strategy:
      fail-fast: false
      matrix:
        include:
          - kubernetes_version: 'v1.20.15'
          - kubernetes_version: 'v1.21.9'
          - kubernetes_version: 'v1.22.6'
          - kubernetes_version: 'v1.23.3'
          - kubernetes_version: 'v1.24.1'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${ env.terraform_version }

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.6.1
        with:
          minikube version: ${{ env.minikube_version }}
          kubernetes version: ${{ matrix.kubernetes_version }}

      - name: Enable Minikube Addons
        run: |
          minikube addons enable ingress
          minikube addons enable csi-hostpath-driver
          minikube addons enable metrics-server

      - name: Print context
        run: kubectl config get-contexts

      - name: Terraform init
        run: terraform init

      - name: Deploy terraform
        working-directory: _example/
        run: terraform apply -auto-approve

